dist: bionic
# Matlab R2020a libstdc++ needs Ubuntu 18.04

language: matlab

matlab:
- latest

git:
- depth: 3
- quiet: true

addons:
  apt:
    packages:
    - gfortran
    - libhdf5-dev
    - liblapack-dev
    - libopenmpi-dev
    - libmumps-dev
  snaps:
  - name: cmake
    confinement: classic

before_script:
- export PATH=/snap/bin:$PATH
