name: matlab

env:
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
    - "**.m"
    - "**.cmake"
    - "**/CMakeLists.txt"
    - "cmake/libraries.json"
    - ".github/workflows/**"
    - "!scripts/**"
    - "!examples/**"

# full tests require >= R2023a

# https://www.mathworks.com/support/requirements/supported-compilers-linux.html

# https://www.mathworks.com/content/dam/mathworks/mathworks-dot-com/support/sysreq/files/system-requirements-release-2021b-supported-compilers.pdf
# R2021a, R2021b: GCC-8

# R2022a..R2024b: GCC-10
# https://www.mathworks.com/content/dam/mathworks/mathworks-dot-com/support/sysreq/files/system-requirements-release-2023a-supported-compilers.pdf


jobs:

  linux:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    # Ubuntu 22.04 GA Linux runner has GCC-10, needed for Matlab R2022a..R2025a

    strategy:
      fail-fast: false
      matrix:
        release: [R2025a, R2023b]

    steps:

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{ matrix.release }}
        cache: true

    - name: Git Checkout ${{ github.action_repository }}
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Run Matlab syntax checks
      if: ${{ matrix.release >= 'R2024a' || startsWith(matrix.release, 'latest') }}
      timeout-minutes: 15
      uses: matlab-actions/run-build@v2
      with:
        tasks: check

    - name: Upload CodeIssues
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.release }}-${{ runner.os }}-codeissues
        path: CodeIssues.sarif

    - uses: ./.github/workflows/composite-pkg
      timeout-minutes: 15

    - uses: ./.github/workflows/composite-gemini3d
      timeout-minutes: 15
      env:
        CMAKE_INSTALL_PREFIX: ${{ github.workspace }}/libs
        CC: gcc-10
        CXX: g++-10
        FC: gfortran-10
    # avoid GLIBCXX conflicts causing subprocess_run to not work

    - name: Run Matlab tests (buildtool)
      timeout-minutes: 15
      uses: matlab-actions/run-build@v2
      env:
        GEMINI_ROOT: ${{ github.workspace }}/libs
        GEMCI_ROOT: ${{ github.workspace }}/gemci
        GEMINI_CIROOT: ${{ github.workspace }}/ci
      with:
        tasks: test
